I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 117, in script
    l "Ask me the questions, bridgekeeper. I am not afraid."
Exception: Sayer 'l' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 117, in script
    l "Ask me the questions, bridgekeeper. I am not afraid."
  File "C:\Users\Александр\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Александр\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'l' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Alert 1.0
Mon Nov 27 01:51:49 2023
